batches_per_step: 20
data:
  url: https://determined-ai-public-datasets.s3-us-west-2.amazonaws.com/PennFudanPed/PennFudanPed.zip
description: pedestrian_detection_single_gpu
entrypoint: model_def:ObjectDetectionTrial
hyperparameters:
  global_batch_size: 2
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005
min_validation_period: 1
searcher:
  max_steps: 20
  metric: val_avg_iou
  name: single
  smaller_is_better: false
